### ISSUE TITLE
enhanced apps not working/autoloading

### ISSUE THREAD

**Issue by lx05** [linuxserver/ifai#1301] opened 2024-02-24 00:02 UTC
Hi together,

i just experienced a strange issue. If I select an application type, nothing is autoloaded. Normally the logo and for some services also additional config is loaded. But now it just stays blank. Why is that?

See images
first is my plex from a few months ago and second one is from today if i try to create a new one:
![plexnormal](https://github.com/linuxserver/Heimdall/assets/60663076/b41ccccf-bcc2-4e92-bd52-090406d91cce)
![plex today](https://github.com/linuxserver/Heimdall/assets/60663076/ece735e8-c096-47b1-a516-da609eb53036)

**Comment by listiges-kaenguru** [comment] 2024-02-26 07:36
While trying this I noticed that it does not reload when I change application-type or between website an application.

Maybe that is the issue. On my tests it look exaktly the same while trying this.

**Comment by mvdkleijn** [comment] 2024-02-27 16:13
I suggest you make sure you have Heimdall updated to latest and have your app list also updated. I closed the related issue because (for better or worse) I cannot reproduce the issue. Works fine for me. (see below screenshot)

If it does work for you, please close this issue. I do not have access to the main Heimdall repo, nor the issues. I only have access to Heimdall-Apps.

![heimdall-Screenshot from 2024-02-27 17-09-25](https://github.com/linuxserver/Heimdall/assets/431452/270ae35b-c3b5-4a37-b34d-7857dcaffc07)

**Closed as not planned** 2024-05-28 15:36 UTC
Labels: no-issue-activity, closed-issue-activity
