### ISSUE TITLE
qBittorrent API doesn't work with the last version

### ISSUE THREAD

**Issue by barzag** [linuxserver/ifai#1055] opened 2022-12-01 11:22 UTC
Hello,

Following the Heimdall update, the qBittorrent API no longer works? Any idea for a fix?

**Comment by joeinertia** [comment] 2022-12-01 14:11
was wondering if this was just me too, do you get any result when testing? unresponsive for me

**Comment by keriati** [comment] 2022-12-01 15:16
It could be a known bug in 2.5.3, what version do you have?

**Comment by barzag** [comment] 2022-12-01 16:37
v2.5.3

**Comment by Llamrei80** [comment] 2022-12-01 16:40
This is a duplicate of #1050 and is fixed in the development build.

**Closed as completed** 2022-12-01 16:56 UTC
